version: '3.7'

services:
  npmjs:
    container_name: npmjs
    restart: always
    build: .
    environment:
      PORT: 80
      PUBLIC_URL: https://npmjs.co.uk
      VIRTUAL_HOST: npmjs.co.uk
      LETSENCRYPT_HOST: npmjs.co.uk
      LETSENCRYPT_EMAIL: hello@jackallen.me
      REACT_APP_API_URL: https://api.npmjs.co.uk
    expose:
      - 80
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: proxy-network
