version: '3.7'

services:
  npmjs-api:
    container_name: npmjs-api
    build: .
    command: yarn start
    environment:
      PORT: 80
    expose:
      - 80
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: proxy-network
