version: '3.7'

services:
  npmjs-api:
    container_name: npmjs-api
    build: .
    command: yarn start
    environment:
      PORT: 80
      PUBLIC_URL: https://api.npmjs.co.uk
      VIRTUAL_HOST: api.npmjs.co.uk
      LETSENCRYPT_HOST: api.npmjs.co.uk
      LETSENCRYPT_EMAIL: hello@jackallen.me
    expose:
      - 80
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: proxy-network
